package com.gateflow.rbac;

public enum Permission {
    WORKFLOW_VIEW,
    WORKFLOW_CREATE,
    WORKFLOW_UPDATE,
    WORKFLOW_PUBLISH,
    REQUEST_SUBMIT,
    REQUEST_VIEW_OWN,
    REQUEST_VIEW_ALL,
    REQUEST_APPROVE,
    REQUEST_WITHDRAW_OWN,
    REQUEST_REASSIGN,
    MEMBERSHIP_MANAGE,
    ROLE_MANAGE,
    AUDIT_VIEW
}
