import { chromium } from 'playwright';
import { readFile } from 'node:fs/promises';
import assert from 'node:assert/strict';
assert.equal(process.env.GATEFLOW_DISPOSABLE_STACK, '1', 'Disposable stack consent required');
assert.ok(process.env.GATEFLOW_LOAD_FIXTURE, 'Private fixture required');
const fixture = JSON.parse(await readFile(process.env.GATEFLOW_LOAD_FIXTURE, 'utf8'));
assert.match(fixture.base, /^http:\/\/(127\.0\.0\.1|localhost)(:\d+)?$/);
const browser = await chromium.launch(process.env.GATEFLOW_CHROMIUM ? { executablePath: process.env.GATEFLOW_CHROMIUM } : {});
const errors = [], failures = [];
try {
  const context = await browser.newContext({ viewport: { width: 1440, height: 1000 } });
  await context.addCookies(Object.entries(fixture.adminCookies).map(([name, value]) => ({ name, value, url: fixture.base, httpOnly: name !== 'XSRF-TOKEN', sameSite: 'Lax' })));
  const page = await context.newPage();
  page.on('pageerror', e => errors.push(e.message));
  page.on('response', r => { if (r.url().includes('/api/') && r.status() >= 500) failures.push(r.status()); });
  await page.goto(fixture.base);
  await page.getByRole('heading', { name: 'Requests', exact: true }).waitFor();
  await page.getByRole('textbox', { name: 'Organization ID', exact: true }).fill(fixture.prefix.split('/').at(-1));
  await page.getByRole('button', { name: 'Open workspace', exact: true }).click();
  await page.getByRole('textbox', { name: 'Search requests', exact: true }).fill('CI laptop');
  await page.getByRole('textbox', { name: 'Search requests', exact: true }).press('Enter');
  await page.getByText('CI laptop', { exact: true }).waitFor();
  await page.getByRole('button', { name: 'Notifications', exact: true }).click();
  await page.getByRole('heading', { name: 'Recent updates', exact: true }).waitFor();
  await page.setViewportSize({ width: 390, height: 844 });
  await page.getByRole('button', { name: 'Open item', exact: true }).first().click();
  await page.getByRole('dialog').waitFor();
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false, 'Mobile overflow');
  await page.getByRole('button', { name: 'Close', exact: true }).click();
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.getByRole('button', { name: 'Workspace setup', exact: true }).click();
  await page.getByRole('button', { name: 'Workflow policies', exact: true }).click();
  await page.getByText('Ordered sequential steps', { exact: true }).waitFor();
  await page.getByRole('button', { name: 'Audit logs', exact: true }).click();
  await page.getByRole('heading', { name: 'Audit evidence', exact: true }).waitFor();
  assert.deepEqual(errors, [], 'Uncaught browser errors');
  assert.deepEqual(failures, [], 'Unexpected server failures');
  await context.close();
  console.log('PASS: real backend browser flow; workspace, requests, notifications, mobile detail, policy administration, audit');
} finally { await browser.close(); }
