export type ApiError={status:number;title:string;detail:string;requestId?:string};
export type User={id:string;email:string;displayName?:string};
let csrf:string|undefined;
async function problem(r:Response):Promise<ApiError>{let b:any={};try{b=await r.json()}catch{b={}}return{status:r.status,title:b.title||'Request failed',detail:b.detail||`HTTP ${r.status}`,requestId:b.requestId}}
export async function api<T>(path:string,init:RequestInit={}):Promise<T>{const method=(init.method||'GET').toUpperCase();if(!csrf&&method!=='GET')await getCsrf();const headers=new Headers(init.headers);if(init.body)headers.set('Content-Type','application/json');if(csrf&&method!=='GET')headers.set('X-XSRF-TOKEN',csrf);const r=await fetch(path,{...init,headers,credentials:'include'});if(!r.ok)throw await problem(r);if(r.status===204)return undefined as T;return r.json()}
export async function getCsrf(){const r=await fetch('/api/v1/auth/csrf',{credentials:'include'});if(!r.ok)throw await problem(r);const b=await r.json();csrf=b.token||b.csrfToken;return b}
export const auth={me:()=>api<User>('/api/v1/auth/me'),login:(email:string,password:string)=>api<User>('/api/v1/auth/login',{method:'POST',body:JSON.stringify({email,password})}),signup:(email:string,password:string,displayName:string)=>api<User>('/api/v1/auth/signup',{method:'POST',body:JSON.stringify({email,password,displayName})}),logout:()=>api<void>('/api/v1/auth/logout',{method:'POST'})};
export const requests={list:(org:string,q:string)=>api<any>(`/api/v1/organizations/${encodeURIComponent(org)}/requests?limit=20&sort=newest${q?`&q=${encodeURIComponent(q)}`:''}`),inbox:(org:string)=>api<any>(`/api/v1/organizations/${encodeURIComponent(org)}/requests/inbox?limit=20&sort=oldest`)};
export const notifications={list:(org:string)=>api<any>(`/api/v1/organizations/${encodeURIComponent(org)}/notifications?limit=20`),count:(org:string)=>api<any>(`/api/v1/organizations/${encodeURIComponent(org)}/notifications/unread-count`)};
