import React,{FormEvent,useEffect,useState} from 'react';import{createRoot}from'react-dom/client';import{ApiError,auth,getCsrf,notifications,requests,User}from'./api';import'./styles.css';import{normalizeItems as rows}from'./view-model';
type View='requests'|'inbox'|'notifications';
function ErrorBox({error}:{error:ApiError|null}){return error?<div className="alert" role="alert"><b>{error.title}</b><span>{error.detail}</span>{error.requestId&&<small>Request {error.requestId}</small>}</div>:null}
function App(){const[user,setUser]=useState<User|null>(null),[boot,setBoot]=useState(true),[error,setError]=useState<ApiError|null>(null),[org,setOrg]=useState(localStorage.getItem('gateflow.org')||''),[view,setView]=useState<View>('requests'),[data,setData]=useState<any>(null),[loading,setLoading]=useState(false),[q,setQ]=useState('');
useEffect(()=>{getCsrf().then(()=>auth.me()).then(setUser).catch(()=>{}).finally(()=>setBoot(false))},[]);
async function load(next=view){if(!org)return;setLoading(true);setError(null);localStorage.setItem('gateflow.org',org);try{setData(await(next==='requests'?requests.list(org,q):next==='inbox'?requests.inbox(org):notifications.list(org)))}catch(e){setError(e as ApiError)}finally{setLoading(false)}}
useEffect(()=>{if(user&&org)void load(view)},[view,user]);
if(boot)return <main className="center"><div className="spinner"/><p>Opening your workspace…</p></main>;
if(!user)return <Auth onUser={setUser}/>;
const items=rows(data);return <div className="shell"><aside><a className="brand" href="#"><span>G</span>GateFlow</a><nav aria-label="Primary">{(['requests','inbox','notifications']as View[]).map(x=><button key={x} className={view===x?'active':''} onClick={()=>setView(x)}>{x==='requests'?'All requests':x==='inbox'?'Review inbox':'Notifications'}</button>)}</nav><div className="profile"><div className="avatar">{(user.displayName||user.email).slice(0,1).toUpperCase()}</div><div><b>{user.displayName||'Account'}</b><small>{user.email}</small></div><button aria-label="Sign out" onClick={()=>auth.logout().finally(()=>setUser(null))}>↗</button></div></aside><main><header><div><p className="eyebrow">Approval workspace</p><h1>{view==='requests'?'Requests':view==='inbox'?'Review inbox':'Notifications'}</h1></div><button className="primary" disabled={!org}>+ New request</button></header><section className="orgbar"><label>Organization ID<input value={org} onChange={e=>setOrg(e.target.value)} placeholder="Paste organization UUID"/></label><button onClick={()=>load()} disabled={!org||loading}>Open workspace</button></section><ErrorBox error={error}/><section className="panel"><div className="toolbar"><div><h2>{view==='requests'?'Request activity':view==='inbox'?'Waiting for your decision':'Recent updates'}</h2><p>{view==='requests'?'Track submitted approvals across your organization.':view==='inbox'?'Oldest items appear first so nothing gets stuck.':'Private updates for requests you can currently access.'}</p></div>{view==='requests'&&<form onSubmit={(e)=>{e.preventDefault();void load()}}><input aria-label="Search requests" value={q} onChange={e=>setQ(e.target.value)} placeholder="Search title or description"/></form>}</div>{loading?<div className="state"><div className="spinner"/>Loading…</div>:!org?<div className="state"><b>Choose an organization</b><span>Enter its ID above to load your authorized workspace.</span></div>:items.length===0?<div className="state"><div className="emptyIcon">✓</div><b>{view==='inbox'?'You’re all caught up':'Nothing here yet'}</b><span>{view==='requests'?'New requests will appear here after submission.':'There are no items requiring attention.'}</span></div>:<div className="list">{items.map((item:any,i:number)=><article key={item.id||i}><span className={`status ${(item.status||'new').toLowerCase()}`}>{item.status||item.type||'Update'}</span><div><h3>{item.title||item.message||'Approval request'}</h3><p>{item.description||item.workflowName||item.action||'Open for details'}</p></div><time>{item.createdAt?new Date(item.createdAt).toLocaleDateString():''}</time><button aria-label="Open item">→</button></article>)}</div>}</section></main></div>}
function Auth({onUser}:{onUser:(u:User)=>void}){const[signup,setSignup]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState<ApiError|null>(null);async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError(null);const f=new FormData(e.currentTarget);try{onUser(signup?await auth.signup(String(f.get('email')),String(f.get('password')),String(f.get('displayName'))):await auth.login(String(f.get('email')),String(f.get('password'))))}catch(x){setError(x as ApiError)}finally{setBusy(false)}}return <main className="auth"><section><a className="brand" href="#"><span>G</span>GateFlow</a><div className="authcopy"><p className="eyebrow">Approvals without the chase</p><h1>Move decisions forward with confidence.</h1><p>One clear workspace for requests, reviewers, evidence, and every step between.</p><ul><li>Versioned approval policies</li><li>Real-time reviewer inbox</li><li>Traceable decision history</li></ul></div><small>Secure by default · Organization scoped</small></section><form onSubmit={submit}><div><p className="eyebrow">Welcome</p><h2>{signup?'Create your account':'Sign in to GateFlow'}</h2><p>{signup?'Start a secure approval workspace.':'Use your work account to continue.'}</p></div><ErrorBox error={error}/>{signup&&<label>Display name<input name="displayName" required autoComplete="name"/></label>}<label>Email<input name="email" type="email" required autoComplete="email"/></label><label>Password<input name="password" type="password" required minLength={12} autoComplete={signup?'new-password':'current-password'}/></label><button className="primary" disabled={busy}>{busy?'Please wait…':signup?'Create account':'Sign in'}</button><button type="button" className="link" onClick={()=>{setSignup(!signup);setError(null)}}>{signup?'Already have an account? Sign in':'New to GateFlow? Create an account'}</button></form></main>}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
